server:
  port: 8083
spring:
  application:
    name: increment-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/increment?transformedBitIsBoolean=true
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
